version: '3.7'

services: 
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - NEW_SECRET_KEY=django-insecure-ynkh$$2u2&g(q#q=f)7t3r1r1+2qdoc2&o8z^^#9kd*xc9tg#6b
      - DEBUG=1
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres:11
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
volumes: 
  postgres_data: